// app/layout.tsx
import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'My Next App',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='{inter.className}'>
        <div className='relative w-full flex items-center justify-center' >
        <Navbar/>
        </div>
        {children}
      </body>
    </html>
  )
}





